### ISSUE TITLE
Pre-beta checklist

### ISSUE THREAD

**Issue by kmdreko** [kmdreko/venator#1]
There are many things I want to either implement or polish-up before pushing out a "beta" release.

These are just the highlights that I would like to keep track of publicly. Many of the UI improvements to make just amount to adding context menus, hover states, buttons, and interactive niceties, but others require adding whole new systems and plumbing:
- [X] tabs improvements
- [X] handle all attribute value types
- [X] details panel improvements
- [X] filter input improvements
- [x] status bar UI
- [X] data management UI
- [x] table improvements
- [x] graph improvements
- [x] time controls improvements
- [x] make native menu do stuff

The goal is that the application will have all currently planned functionality working and complete for the beta release. After that, I will focus on making it more robust, performant, and maintainable in preparation for a 1.0 release. As always, feedback is welcome at any time.
